In [46]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

# Quick sanity check
x = np.array([[1], [2], [3], [4]])
y = np.array([2, 4, 6, 8])

model = LinearRegression().fit(x, y)
print(f"Model slope: {model.coef_[0]:.1f}")

Model slope: 2.0


In [ ]:

print(np.__version__)

2.5.3


In [47]:
array = np.array([[1, 2, 3],
                  [1, 2, 3], 
                  [1, 2, 3]])

print(array.ndim)
print(array.shape)
# n layers, n rows, n columns

2
(3, 3)


In [ ]:
# slicing
array = np.array([[1,  2,  3,  4],
                  [5,  6,  7,  8],
                  [9, 10, 11, 12],
                  [13, 14, 15, 16]])

# array[start:end:step]

print(array[1:4:2])
print(" ")
print(array[: , 1])
print(" ")
print(array[1, :])
print(" ")
# first 2 cols, rows
print(array[:2, :2])

[[ 5  6  7  8]
 [13 14 15 16]]
 
[ 2  6 10 14]
 
[5 6 7 8]
 
[[1 2]
 [5 6]]


In [26]:
#Scalar arthemetic in numpy

array = np.array([1, 2, 3])
scores = np.array([1, 2, 3])

print(array ** 2)

# Vectorized math functions

print(np.sqrt(array))

# operations on multiple arrays

# comparision operators
scores[scores > 2] = 0
print(scores)


[1 4 9]
[1.         1.41421356 1.73205081]
[1 2 0]


In [27]:
# Broadcasting allows Numpy to perform operations on arrays
# with different shapes by virtually expanding on arrays

array1 = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [1, 2, 3, 4],
                   [5, 6, 7, 8]])
array2 = np.array([[1], [2], [3], [4]])

# NOTE : not all arrays are compatible with broadcasting

print(array1.shape)
print(array2.shape)

print(array1 * array2)

(4, 4)
(4, 1)
[[ 1  2  3  4]
 [10 12 14 16]
 [ 3  6  9 12]
 [20 24 28 32]]


In [30]:
# aggregate functions = summarise data and typically return a single value

Array = np.array([[1, 2, 3, 4, 5],
                 [6, 7, 8, 9, 10]])

# np.sum(Array)
# np.mean(Array)
# np.std(Array)
# np.var(Array)
# min, max, argmin(for coords of min element)

print(np.sum(Array, axis=0))





[ 7  9 11 13 15]


In [ ]:
# Filtering

good = Array[Array < 8]
print(good)
print(" ")
high = np.where(Array >=7, Array, 0)        # this preserves the shape of the array instead of flattning
print(high)

[1 2 3 4 5 6 7]
 
[[ 0  0  0  0  0]
 [ 0  7  8  9 10]]


In [ ]:
# Random numbers

rng = np.random.default_rng()  # we can use seed if we want to reproduce the same results

print(rng.integers(low=1, high=101, size =(3, 2)))


[[98 69]
 [77 92]
 [ 8 38]]


In [ ]:
# Misc for the assignment

#In NumPy, a 1D array of shape (N,) is neither a row vector nor a column vector. If you need it as an explicit column vector R^Nx1
y = np.array([2.1, 3.8, 6.2, 7.9])
print(y.shape)
y_col = y.reshape(-1, 1)  # Shape becomes (4, 1)
print(y.shape)

(4,)
(4,)


In [43]:
# matrix multiplication

X = np.array([
             [1.0, 2.0],
             [3.0, 4.0],
             [5.0, 6.0],
             [7.0, 8.0]
                      ])
w = np.array([[0.5], [1.2]])
y_hat = X @ w
print(y_hat)

[[ 2.9]
 [ 6.3]
 [ 9.7]
 [13.1]]


In [45]:
# Transpose of a Matrix

X_transpose = X.T
print(X_transpose)

[[1. 3. 5. 7.]
 [2. 4. 6. 8.]]
